requires 'Hash::Merge'         => '<=0.200';
requires 'Jifty'               => '1.50430';
requires 'Jifty::DBI'          => '0.78';
requires 'Text::Markdown'      => 0;
requires 'Digest::SHA'         => 0;
requires 'XML::Feed'           => 0;
requires 'Text::Emoticon::MSN' => 0.04;
requires 'List::MoreUtils'     => 0.22;
requires 'HTML::TagCloud'      => 0;
