distribution_type: module
generated_by: Module::Install version 0.64
license: unknown
name: Bifty
no_index:
  directory:
    - inc
    - t
requires:
  Digest::SHA: 0
  Jifty: 0.60722
  List::MoreUtils: 0.22
  Text::Emoticon::MSN: 0.04
  Text::Markdown: 0
  XML::Feed: 0
version: 0.01
